spring:
  datasource:
    password: 7431282
    username: root
    url: 'jdbc:mysql://localhost:3307/fornecedor-paper?useTimezone=true&serverTimezone=UTC'
  jpa:
    hibernate:
      ddl-auto: update
